Repository matodorovic/kino-ytterhogdal, pull requests merged in 2021-12, with the labels that each got.

#88 add footer to index.html with temporary content
  index.html
  main.css
  main.css.map
  main.scss
  sections/footer.scss
Labels: enhancement, good first issue

#90 Navbar
  index.html
  main.css
  main.css.map
  main.scss
  sections/_nav.scss
Labels: good first issue

#93 Added variables in sass
  .gitignore
  main.scss
  sections/_variables.scss
  sections/variables.scss
Labels: good first issue

#96 add styling to menu buttons
  index.html
  main.css
  main.css.map
  sections/_nav.scss
Labels: enhancement

#97 Logo
  index.html
  main.css
  main.css.map
  main.scss
  sections/_logo.scss
  src/img/gm.png
Labels: enhancement

#100 Social media
  index.html
  main.css
  main.css.map
  sections/_footer.scss
  sections/_variables.scss
Labels: 1 EP

#105 About us
  aboutus.html
  img/gm.png
  main.css
  main.css.map
  main.scss
  sections/_aboutus.scss
  sections/_nav.scss
Labels: enhancement, 2 EP

#101 Nav search
  .DS_Store
  index.html
  main.css
  main.css.map
  main.scss
  src/scss/index.css
Labels: enhancement

#112 Hover for all the buttons - shadow and font color change
  main.css
  main.css.map
  sections/_aboutus.scss
  sections/_footer.scss
  sections/_nav.scss
Labels: enhancement, 1 EP

#110 Added alternative text to all images
  aboutus.html
  index.html
  package.json
Labels: enhancement, 2 EP

#108 Heroku
  app.js
  bundle.js
  img/hero.png
  img/logo-on-red.png
  index.html
  main.css
  package.json
  sections/_hero.scss
Labels: 3 EP

#109 modified content in title tag
  aboutus.html
  index.html
Labels: enhancement

#111 History
  aboutus.html
  img/oldcinema.jpg
  index.html
  main.css
  main.css.map
  main.scss
  sections/_aboutus.scss
  sections/_importantInfo.scss
  sections/_nav.scss
Labels: enhancement, 3 EP
